# Generated by Django 5.2.15 on 2026-06-14 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=48)),
                ("avatar_url", models.URLField(blank=True)),
                ("persona_card", models.JSONField(default=dict)),
                ("system_prompt", models.TextField()),
                (
                    "model_id",
                    models.CharField(default="llama-3.3-70b-versatile", max_length=64),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("sfw", "SFW"),
                            ("flirty", "Flirty"),
                            ("spicy", "Spicy"),
                        ],
                        default="sfw",
                        max_length=16,
                    ),
                ),
                ("allowed_tags", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonaMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facts", models.JSONField(default=dict)),
                ("rolling_summary", models.TextField(blank=True)),
                ("last_window", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="bots.persona",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "persona")},
            },
        ),
    ]
