# Generated by Django 5.2.15 on 2026-06-14 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=48, unique=True)),
                ("label", models.CharField(max_length=48)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mood", "Mood"),
                            ("topic", "Topic"),
                            ("spice", "Spice Level"),
                            ("language", "Language"),
                            ("region", "Region"),
                            ("time", "Time of Day"),
                            ("custom", "Custom"),
                        ],
                        default="topic",
                        max_length=16,
                    ),
                ),
                ("is_user_created", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tags",
                        to="tags.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["category", "usage_count"], name="tags_tag_categor_2e1384_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertag",
            unique_together={("user", "tag")},
        ),
    ]
