# Generated by Django 5.2.15 on 2026-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_honeypot",
            field=models.BooleanField(default=False),
        ),
    ]
