# Generated by Django 5.2.15 on 2026-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
