# Generated by Django 5.2.15 on 2026-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_summary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="typing_a_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="typing_other_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
