# Generated by Django 5.2.15 on 2026-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_typing_a_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="behavior_signals",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
