# Generated by Django 5.2.15 on 2026-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_behavior_signals"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="soft_flag",
            field=models.BooleanField(default=False),
        ),
    ]
